include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_print: true
    use_key_in_widget_constructors: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_unnecessary_containers: true
    prefer_collection_literals: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_this: true
    use_build_context_synchronously: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
  errors:
    invalid_annotation_target: ignore
